title: Janeraka
email: info@janeraka.org
description: >- # this means to ignore newlines until "baseurl:"
  Lorem Ipsum
baseurl: ''
description-pt: Acolhimento para Povos da Floresta em Trânsito
description-en: [pending]
basecolor: '#000000' # for browser settings
url: 'https://janeraka.org'
twitter_username: 
github_username: 

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock