title: Janeraka
email: info@janeraka.org
# description: >- # this means to ignore newlines until "baseurl:"
#   Lorem Ipsum
baseurl: ''
description:
  pt: Acolhimento para Povos da Floresta em Trânsito
  en: Shelter for Forest People in transit
basecolor: '#000000' # for browser settings
url: 'https://janeraka.org'

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock

donations:
  monthly-en:
    - value: 5
      link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QEYKGU7E6N8WQ
      delay: 0ms
    - value: 15
      link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=AZQZRSY4CXW6Q
      delay: 300ms
    - value: 25
      link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BBHT55BVNSZ72
      delay: 600ms
    - value: custom
      link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TC5WE2JAXKX3G&source=url
      delay: 900ms
  single-en:
    - value: 5
      link: xxx
      delay: 0ms
    - value: 15
      link: xxx
      delay: 300ms
    - value: 25
      link: xxx
      delay: 600ms
    - value: custom
      link: xxx
      delay: 900ms

team: 
  - name: Nicholas Frota
    email: info@nicholasfrota.com
    role: 
      pt: designer e gerente de projeto
      en: graphic designer and project manager
    social:
      - name: site
        url: https://praxis.nyc
      - name: mastodon
        url: https://mastodon.social/@nonlinear
      - name: twitter
        url: https://twitter.com/nonlinear
      - name: instagram
        url: https://instagram.com/nonlinear

  - name: Danilo Vaz
    email: dnllvrvz@gmail.com
    role: 
      pt: integrações, DNS
      en: integrations, DNS
    # social:
    #   - name: site
    #     url: https://praxis.nyc
    #   - name: mastodon
    #     url: https://mastodon.social/@nonlinear
    #   - name: twitter
    #     url: https://twitter.com/nonlinear
    #   - name: instagram
    #     url: https://instagram.com/nonlinear

  # - name: Rodney Silva
  #   email: rodney@thinks.com.br
  #   role: 
  #     pt: integrações, comércio eletrônico
  #     en: integrations, e-commerce
    # social:
    #   - name: site
    #     url: https://praxis.nyc
    #   - name: mastodon
    #     url: https://mastodon.social/@nonlinear
    #   - name: twitter
    #     url: https://twitter.com/nonlinear
    #   - name: instagram
    #     url: https://instagram.com/nonlinear

