title: Janeraka
email: info@janeraka.org
# description: >- # this means to ignore newlines until "baseurl:"
#   Lorem Ipsum
baseurl: ''
description:
  pt: Acolhimento para Povos da Floresta em Trânsito
  en: Shelter for People of the Forest in transit
basecolor: '#000000' # for browser settings
url: 'https://janeraka.org'

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
